on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy app to gh pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12' 
      - name: Node Install
        run: npm run deploy
